name: FrontEnd CICD 

on: push

jobs:
  markdown-link-check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1

  update_s3_web_files:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update Object in S3 Bucket
        run: |
          aws s3 sync front-end s3://${{ env.AWS_S3_BUCKET }}/
